openapi: 3.0.3
info:
  title: Football League Service
  description: Please note that all api operation return 200 HTTP code, each respond data contains different identity code. So in this specification, the respond code is as same as the identity code field in the respond data.
  contact:
    name: API Support
    email: leminhhuy.hcmus@gmail.com
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: ''

tags:
  - name: HealthCheck
    description: Find out basic information of the service
  - name: Auth

paths:
  /health-check:
    get:
      tags:
        - HealthCheck
      description: Find out basic information of the service
      operationId: updatePet
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: 'OK'
                  data:
                    type: object
                    properties:
                      service:
                        type: string
                      version:
                        type: string
                        example: 'v1'

  /auth/login:
    post:
      tags:
        - Auth
      summary: Login by username/password
      operationId: baseLogin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseLoginForm'
      responses:
        '200':
          description: :ogin success
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: object
                    properties:
                      accessToken:
                        type: string
                      refreshToken:
                        type: string
                      idToken:
                        type: string
                      expireIn:
                        type: number
                      expireAt:
                        type: string
                  user:
                    type: object
                    properties:
                      fullname:
                        type: string
              example:
                token:
                  accessToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6ImxlYWd1ZXM6YWxsIiwicm9sZSI6MCwidXNlcklkIjoiNjI0ZmRmOGU4OWNhZjNmOWQ2MzY2ZjQ3IiwiaWF0IjoxNjg3MzY0NDE1LCJleHAiOjE2ODczNjgwMTV9.4ze-UE_q6BEkMesf0QGnwF-ipfDJWGdhmEkCWKXn9-E'
                  refreshToken: 'b04b1c73737cdd739649412538a72f0a2a3fb51f9f84a18ba717e0fcd63bacf4ef2fa1e94c69cbdd32c27f1298e05ee48a93245c2eaf41f50ef99cf0f8a7971aef94294e1749a0cb18f37582cf82f2bd'
                  idToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9vZGF5MUBmZGEuZ292IiwiZnVsbG5hbWUiOiJPZGUgTydEYXkiLCJpYXQiOjE2ODczNjQ0MTUsImV4cCI6MTY4Nzk2OTIxNSwiaXNzIjoiaHR0cHM6Ly9mb290YmFsbGxlYWd1ZXNlcnZpY2Uub25yZW5kZXIuY29tIiwic3ViIjoiNjI0ZmRmOGU4OWNhZjNmOWQ2MzY2ZjQ3In0.dDiEg7WWBbGJMSYxv8JFuB5CAX_yAfrfg9TF7c-bKTM"
                  expireIn: 3600000
                  expireAt: 2023-06-21T17:20:16.087Z
                user:
                    fullname: Ode O'Day

        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponse'
                type: object
                properties:
                  data:
                    type: string
              example:
                code: 400
                message: Bad Request
                data: Thiếu tên đăng nhập

components:
  schemas:
    BaseResponse:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
        metadata:
          type: object
          properties:
            createdDate:
              type: string
              example: 2023-06-21T16:08:56.318Z
    BaseLoginForm:
      type: object
      properties:
        username:
          type: string
        password:
          type: string

  securitySchemes:
    access_token:
      type: http
      scheme: Bearer
